hmcts/hmc-hmi-outbound-adapter

src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
src/integrationTest/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepositoryIT.java
src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/HearingManagementInterfaceApiClient.java
src/main/java/uk/gov/hmcts/reform/hmc/controllers/TempController.java
src/main/java/uk/gov/hmcts/reform/hmc/repository/DefaultFutureHearingRepository.java
src/main/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepository.java
src/test/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepositoryTest.java

https://tools.hmcts.net/jira/browse/HMAN-5
```
[ ] Yes
[X] No
```

HMAN-5 HMC Outbound Adapter - delete a hearing request message

---

src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
src/integrationTest/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepositoryIT.java
src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/HearingManagementInterfaceApiClient.java
src/main/java/uk/gov/hmcts/reform/hmc/controllers/TempController.java
src/main/java/uk/gov/hmcts/reform/hmc/repository/DefaultFutureHearingRepository.java
src/main/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepository.java
src/test/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepositoryTest.java

Merge in delete endpoint 

---

charts/hmc-hmi-outbound-adapter/values.yaml

Disable ASB creation on higher envs

---

charts/hmc-hmi-outbound-adapter/Chart.yaml
charts/hmc-hmi-outbound-adapter/values.yaml

Update key vault secret mappings

---

config/owasp/suppressions.xml
src/main/resources/application.yaml

Update config import path

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-1565
```
[ ] Yes
[ ] No
```

Nightly ccd 1565

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties
dependency-check-suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-1600
```
[ ] Yes
[X] No
```

CCD-1600 : Fortify Scan implementation for HMI Outbound Adapter

---

Jenkinsfile_CNP
build.gradle
queue-writer-util/build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/OutboundAdapterTestAutomationAdapter.java
src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/TestDataLoaderMain.java

https://tools.hmcts.net/jira/browse/CCD-2451
Removing jcenter due to [shutdown](https://blog.gradle.org/jcenter-shutdown)
```
[ ] Yes
[ x] No
```

Update to build.gradle

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2594
Suppressing:
CVE-2021-44832, CVE-2021-42550, CVE-2021-43797, CVE-2021-22060, CVE-2022-23181
```
[ ] Yes
[ x] No
```

CCD-2594: Suppress CVE pending investigation

---

charts/hmc-hmi-outbound-adapter/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```

update heml version

---

charts/hmc-hmi-outbound-adapter/Chart.yaml

Upgrade to Latest Base Helm Charts

---

build.gradle
charts/hmc-hmi-outbound-adapter/Chart.yaml
charts/hmc-hmi-outbound-adapter/values.preview.template.yaml
charts/hmc-hmi-outbound-adapter/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
src/integrationTest/java/uk/gov/hmcts/reform/hmc/repository/FutureHearingRepositoryIT.java
src/integrationTest/resources/application-itest.yaml
src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/ErrorDetails.java
src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/FutureHearingErrorDecoder.java
src/main/java/uk/gov/hmcts/reform/hmc/config/MessageReceiverConfiguration.java
src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfiguration.java
src/main/java/uk/gov/hmcts/reform/hmc/config/SyncMessage.java
src/main/java/uk/gov/hmcts/reform/hmc/errorhandling/BadFutureHearingRequestException.java
src/main/java/uk/gov/hmcts/reform/hmc/service/MessageProcessor.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/ApplicationParamsTest.java
src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/FutureHearingErrorDecoderTest.java
src/test/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorTest.java

HMAN-137 - Queue sync responses from HMI

---

src/integrationTest/java/uk/gov/hmcts/reform/hmc/WiremockFixtures.java
src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/HearingManagementInterfaceRequestInterceptor.java
src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/HearingManagementInterfaceRequestInterceptorTest.java

https://tools.hmcts.net/jira/browse/HMAN-141
update DateTimeFormat to yyyy-MM-dd'T'HH:mm:ssXXX 
```
[ ] Yes
[ ] No
```

HMAN-141 update DateTimeFormat to yyyy-MM-dd'T'HH:mm:ssXXX 

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-2926
CVE-2022-21724
```
[ ] Yes
[ X] No
```

Bump Spring Framework to 5.3.18

---

config/owasp/suppressions.xml

There are several dependency check failures, this change is suppressing them.
```
[ ] Yes
[x] No
```

cve multiple issues suppression

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-267
https://tools.hmcts.net/jira/browse/HMAN-266
```
[ ] Yes
[ ] No
```

HMAN-267 HMAN-266 temporarily suppress CVE

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/hmc/config/MessageReceiverConfiguration.java

https://tools.hmcts.net/jira/browse/HMAN-255
increase test coverage for outbound microservice
```
[ ] Yes
[x] No
```

HMAN-255 - increase test coverage for outbound microservice

---

build.gradle

Update azure-messaging-servicebus to latest

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-288
Suppression added for CVE-2022-22978
```
[ ] Yes
[x ] No
```

CCD-3334 RPO Suppression added for CVE-2022-22978

---

src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/FutureHearingErrorDecoder.java
src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/FutureHearingErrorDecoderTest.java

Log HTTP code to help debug FH errors

---

src/main/java/uk/gov/hmcts/reform/hmc/client/futurehearing/FutureHearingErrorDecoder.java
src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/FutureHearingErrorDecoderTest.java

Add some more logging for failed HMI requests

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-440
Suppress
https://nvd.nist.gov/vuln/detail/CVE-2022-42003
https://nvd.nist.gov/vuln/detail/CVE-2022-42004
```
[ ] Yes
[x] No
```

HMAN-440 Suppress CVE-2022-42003, CVE-2022-42004

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-423
https://tools.hmcts.net/jira/browse/HMAN-439
HMAN-439 CVE-2022-42003, CVE-2022-42004 and HMAN-423 CVE-2022-38749, CVE-2022-38750, CVE-2022-38751, CVE-2022-38752 suppressions
```
[ ] Yes
[ x] No
```

HMAN-423 HMAN-439 Suppressions

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-423
https://tools.hmcts.net/jira/browse/HMAN-434
HMAN-433 - fix [CVE-2022-38752](https://github.com/advisories/GHSA-9w3m-gqgf-c4p9) - updated snakeyaml to version 1.32
HMAN-423 - fix CVE-2022-38751 CVE-2022-38750 CVE-2022-38749  - - updated snakeyaml to version 1.32
```
[ ] Yes
[ ] No
```

HMAN-423, HMAN-434  

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-455
https://tools.hmcts.net/jira/browse/HMAN-454
Fix for snakeyaml - CVE-2022-41854
Fix for Tomcat - CVE-2022-42252
Fix for  Spring Security - CVE-2022-31690, CVE-2022-31692
```
[ ] Yes
[ x] No
```

HMAN-455,HMAN-454: Tomcat and Spring Security 

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfiguration.java
src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
src/main/java/uk/gov/hmcts/reform/hmc/errorhandling/ServiceBusMessageErrorHandler.java
src/main/java/uk/gov/hmcts/reform/hmc/service/MessageProcessor.java
src/test/java/uk/gov/hmcts/reform/hmc/client/featurehearing/ServiceBusMessageErrorHandlerTest.java

[HMAN-442](https://tools.hmcts.net/jira/browse/HMAN-442)
Merge of branch HMAN-441 and master
```
[ ] Yes
[X] No
```

Merge of branch HMAN-441 and master

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-417
Fix hmc-hmi-outbound-adapter CVEs and move false positives (15 total) to false positives section.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

Fix hmc-hmi-outbound-adapter CVEs

---

config/owasp/suppressions.xml

CVE suppression added

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-500
CVE-2021-4277 suppression
```
[ ] Yes
[ x] No
```

Hman 500 CVE 2021 4277 suppression

---

.dependabot/dependency-check.yml
.github/workflows/dependency-check.yml
build.gradle
config/owasp/suppressions.xml
gradle/suppress.gradle

https://tools.hmcts.net/jira/browse/HMAN-494
Add suppressCves task
```
[ ] Yes
[ ] No
```

HMAN-494 Add suppressCves task

---

charts/hmc-hmi-outbound-adapter/Chart.yaml

https://tools.hmcts.net/jira/browse/HMAN-518
Upgrade base charts
```
[ ] Yes
[X] No
```

HMAN-518 Upgrade base charts

---

charts/hmc-hmi-outbound-adapter/Chart.yaml

https://tools.hmcts.net/jira/browse/HMAN-533
Bump chart Java
```
[ ] Yes
[X] No
```

HMAN-533: Update Chart.yaml

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-530
CVE-2023-20861 for hmc repos
```
[ ] Yes
[ ] No
```

HMAN-530- CVE-2023-20861

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-541
bumped version of jetty and removed suppressions
```
[ ] Yes
[X] No
```

HMAN-541 : bumped version of jetty and removed suppressions

---

src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java

https://tools.hmcts.net/jira/browse/HMAN-586
review dynatrace logging statements
```
[ ] Yes
[ ] No
```

HMAN-586 : review dynatrace logging statements

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4994
bumped jetty version to 9.4.53
```
[ ] Yes
[X] No
```

CCD-4994 : Fix-CVE-2023-36478

---

acb.tpl.yaml

https://tools.hmcts.net/jira/browse/HMAN-602
Add retries to manifest-create
```
[ ] Yes
[ x] No
```

HMAN-602 : Add retries to manifest-create

---

acb.tpl.yaml

https://tools.hmcts.net/jira/browse/HMAN-602
Remove keep:true acb config to fix retry issue
```
[ ] Yes
[ x] No
```

Remove keep:true acb config

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-607
CVE-2023-28709
CVE-2023-34034
CVE-2023-41080
CVE-2023-42794
CVE-2023-42795
CVE-2023-45648
CVE-2023-45960
CVE-2023-46589
CVE-2023-6378
CVE-2023-3635
CVE-2023-35116
```
[ ] Yes
[ ] No
```

HMAN-607: CVE-2023 bumps

---

src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfiguration.java
src/main/java/uk/gov/hmcts/reform/hmc/service/MessageProcessor.java

https://tools.hmcts.net/jira/browse/HMAN-639
Add more logs to debug
```
[ ] Yes
[ ] No
```

HMAN-639 - add logs to debug

---

build.gradle
config/owasp/suppressions.xml

CVE-2023-35116 Fix CVE for HMC repo's
Investigate and fix the vulnerability reported for CVE-2023-35116
```
[ ] Yes
[x] No
```

HMAN-659 Remove CVE-2023-35116 suppression

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/HMAN-679
fix CVE-2023-44487
```
[ ] Yes
[x] No
```

HMAN-679 fix CVE-2023-44487

---

charts/hmc-hmi-outbound-adapter/Chart.yaml

NA
Bump service bus to 1.0.6 to fix master
```
[ ] Yes
[X] No
```

Bump service bus to 1.0.6 to fix master

---

charts/hmc-hmi-outbound-adapter/Chart.yaml

To allow Azure Service Operator to be upgraded
```
[ ] Yes
[ ] No
```

Chart upgrades

---

build.gradle
queue-writer-util/src/main/java/queue/QueueWriter.java
src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderConfiguration.java
src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java

https://tools.hmcts.net/jira/browse/HMAN-873
Hearings not getting created on demo for SSCS
```
[ ] Yes
[ ] No
```

HMAN-873 - Update Azure library to address AMQP exception

---

charts/hmc-hmi-outbound-adapter/Chart.yaml
charts/hmc-hmi-outbound-adapter/values.yaml
lib/applicationinsights.json

Fix appinsights

---

charts/hmc-hmi-outbound-adapter/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```

CCD-6193 update base chart version

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-6283
https://tools.hmcts.net/jira/browse/CCD-6279
https://tools.hmcts.net/jira/browse/CCD-6280
https://tools.hmcts.net/jira/browse/CCD-6278
https://tools.hmcts.net/jira/browse/CCD-6281
https://tools.hmcts.net/jira/browse/CCD-6284
https://tools.hmcts.net/jira/browse/CCD-6282
```
[ ] Yes
[X] No
```

CCD-6283 Suppress CVE

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-6362
Updated suppression
```
[ ] Yes
[X] No
```

CCD-6362: Update suppressions.xml

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-6374
```
[ ] Yes
[ ] No
```

CVE_supression

---

src/main/java/uk/gov/hmcts/reform/hmc/repository/PendingRequestRepository.java
src/main/java/uk/gov/hmcts/reform/hmc/service/MessageProcessor.java
src/test/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorTest.java

https://tools.hmcts.net/jira/browse/HMAN-997
Change Transactional in PendingRepository
```
[ ] Yes
[ ] No
```

HMAN-997 - potential duplicate request being sent to HMI

---

src/main/java/uk/gov/hmcts/reform/hmc/repository/PendingRequestRepository.java
src/main/java/uk/gov/hmcts/reform/hmc/service/MessageProcessor.java
src/main/java/uk/gov/hmcts/reform/hmc/service/PendingRequestService.java
src/main/java/uk/gov/hmcts/reform/hmc/service/PendingRequestServiceImpl.java
src/test/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorTest.java
src/test/java/uk/gov/hmcts/reform/hmc/service/PendingRequestServiceImplTest.java

https://tools.hmcts.net/jira/browse/HMAN-1006
potential duplicate request being sent to HMI
```
[ ] Yes
[ ] No
```

Claim pending requests during processing

---

src/main/java/uk/gov/hmcts/reform/hmc/model/HmcHearingResponse.java
src/main/java/uk/gov/hmcts/reform/hmc/model/HmcHearingUpdate.java

https://tools.hmcts.net/jira/browse/HMAN-1035
Code change to correct the Exception messages from HMC - Incorrect format
```
[ ] Yes
[ ] No
```

HMAN-1035 - Add JsonNaming for HearingUpdate
